apiVersion: v2
name: presentation
description: Helm chart used for thesis presentation

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "latest"

dependencies:
- name: free5gc-mongodb
  condition: deployMongoDb
- name: free5gc-amf
  condition: deployAmf
- name: free5gc-ausf
  condition: deployAusf
- name: free5gc-n3iwf
  condition: deployN3iwf
- name: free5gc-nrf
  condition: deployNrf
- name: free5gc-nssf
  condition: deployNssf
- name: free5gc-pcf
  condition: deployPcf
- name: free5gc-smf
  condition: deploySmf
- name: free5gc-udm
  condition: deployUdm
- name: free5gc-udr
  condition: deployUdr
- name: free5gc-upf
  condition: deployUpf
- name: free5gc-webui
  condition: deployWebui
- name: free5gc-dbpython
  condition: deployDbPython
